[package]
name = "distaff"
version = "0.5.1"
authors = ["Bobbin Threadbare <bobbinth@protonmail.com>"]
edition = "2018"
description="Zero-knowledge virtual machine written in Rust"
readme="https://github.com/GuildOfWeavers/distaff/blob/master/README.md"
repository = "https://github.com/GuildOfWeavers/distaff"
license = "MIT"

[lib]
name = "distaff"
path = "src/lib.rs"

[[bench]]
name = "all"
harness = false

[dependencies]
hex = "0.4.2"
rand = "0.7.3"
crossbeam-utils = "0.7.2"
bincode = "1.3.1"
serde = { version = "1.0.114", features = ["derive"] }
log = "0.4.11"
env_logger = "0.7.1"
serde_json = "*"
tiny-keccak = { version = "2.0", features = ["sha3"] }

[dev-dependencies]
criterion = "0.3.3"
num-bigint = "0.3.0"